name: pkgdeploy-flaskapp
format: deb
distribution: ubuntu18
architecture: 64-bit
description: A simple flask project to show how PKG Deploy works
url: https://www.pkgdeploy.com
license: GPLv3
maintainer: PKG Deploy Devs <devs@pkgdeploy.com>

build:
  directory: /opt/pkgdeploy/flaskapp/
  requires:
    - python3-pip
    - python3-venv
  commands: |
    python3 -m venv ./venv/
    ./venv/bin/pip install -r requirements.txt

install:
  requires:
    - python3
    - nginx
  user: pkgdeploy
  group: pkgdeploy
  copy:
    - source: ./
      destination: /opt/pkgdeploy/flaskapp/
      user: pkgdeploy
      group: pkgdeploy
      permissions: 755
    - source: nginx.conf
      destination: /etc/nginx/conf.d/flaskapp.conf
    - source: flaskapp.service
      destination: /etc/systemd/system/flaskapp.service

after_install: |
  unlink /etc/nginx/sites-enabled/default
  systemctl enable --now nginx
  nginx -s reload
  systemctl enable --now flaskapp

after_upgrade:
  - file: .pkgdeploy/upgrade_commands.sh
